name: Build node-exporter

on:
  push:
    paths:
      - 'src/vmagent/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install NFPM
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install -qy nfpm
      
      - name: Build
        run: bash -x build.sh
        working-directory: src/vmagent

      - name: Build deb package
        run: nfpm pkg --packager deb -f nfpm.yaml
        working-directory: src/vmagent

      - name: 'Upload packages'
        working-directory: src/vmagent
        env:
          REPO_UPLOAD_ADDR: ${{ secrets.REPO_UPLOAD_ADDR }}
          REPO_USER_NAME: ${{ secrets.REPO_USER_NAME }}
          REPO_USER_PASS: ${{ secrets.REPO_USER_PASS }}
        run: ../../tools/upload.sh
