name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app_name:
          - node-exporter
          - blackbox-exporter

    steps:
      - uses: actions/checkout@v2

      - name: Install NFPM
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install -qy nfpm
      
      - name: Build
        run: bash -x build.sh
        working-directory: src/${{ matrix.app_name }}

      - name: Build deb package
        run: nfpm pkg --packager deb -f nfpm.yaml
        working-directory: src/${{ matrix.app_name }}

      - name: Upload packages
        working-directory: src/${{ matrix.app_name }}
        env:
          CRAFT_USER_NAME: ${{ secrets.CRAFT_USER_NAME }}
          CRAFT_USER_PASS: ${{ secrets.CRAFT_USER_PASS }}
        run: |
          wget https://github.com/vitalvas/craft/raw/master/upload_pkg.sh
          for pkgfullname in $(ls *.deb); do
            bash upload_pkg.sh prometheus ${pkgfullname}
          done
