name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app_name:
          - node-exporter
    
    steps:
      - uses: actions/checkout@v2

      - name: Install NFPM
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install -qy nfpm
      
      - name: Build
        run: bash -x build.sh
        working-directory: src/${{ matrix.app_name }}

      - name: Make
        run: bash -x make.sh ${{ matrix.app_name }}
